<a href="https://colab.research.google.com/github/yakhyo018/Numpy-ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:

import pandas as pd

In [59]:
# 1. DataFrame yaratish
mydataset = {
    "cars": ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    "counts": [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [60]:
# 2. Birinchi qatorlarni ko'rish
df.head()       # Default: 5 ta qator
df.head(3)      # Birinchi 3 ta qator

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2

In [61]:
# 3. Oxirgi qatorlarni ko'rish
df.tail()       # Default: oxirgi 5 ta qator
df.tail(3)      # Oxirgi 3 ta qator
df.tail(-1)     # Asl notebookdagi misol

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [62]:
# 4. DataFrame o'lchami
df.shape        # (qatorlar soni, ustunlar soni)

(7, 2)

In [63]:
# 5. Ustun nomlari
df.columns

Index(['cars', 'counts'], dtype='object')

In [64]:
# 6. Ustunlarning ma'lumot turlari
df.dtypes

cars      object
counts     int64
dtype: object

In [65]:
# 7. DataFrame'ni chiqarish
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [66]:
# 8. Statistik ma'lumotlar
df.describe()   # Sonli ustunlarning statistikasi

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [67]:
# 9. Indeks orqali qatorlarni olish
df.iloc[2:]     # 2-indeksdan oxirigacha

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [68]:
# 10. Label orqali ma'lumot olish
df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [69]:
# 11. Shart bo'yicha filtrlash
df[df["cars"] == "Tesla"]

    cars  counts
3  Tesla       8

In [70]:
# 12. O'rtacha qiymat
df["counts"].mean()

np.float64(4.714285714285714)

In [71]:
# 13. Yig'indi
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [72]:
# 14. Eng kichik qiymat
df.min()

cars      BMW
counts      1
dtype: object

In [73]:
# 15. Eng katta qiymat
df.max()

cars      Volvo
counts        9
dtype: object

In [74]:
# 16. Mediana
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [75]:
# 17. Bo'sh bo'lmagan qiymatlar soni
df.count()

cars      7
counts    7
dtype: int64

In [76]:
# 18. Standart og'ish
df.std(numeric_only=True)

counts    3.199702
dtype: float64

In [77]:
# 19. Bo'sh qiymatli DataFrame yaratish
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [78]:
# 20. Bo'sh qiymatlarni aniqlash
df_missing.isnull()

    cars  counts
0  False   False
1  False   False
2   True    True
3  False   False
4  False   False
5   True   False
6  False    True

In [79]:
# 21. Har bir ustundagi bo'sh qiymatlar soni
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [80]:
# 22. Bo'sh qiymatli qatorlarni olib tashlash
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [81]:
# 23. Bo'sh qiymatlarni to'ldirish
df_missing.fillna({
    "cars": "unknown",
    "counts": 0
})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [82]:
# 24. Excel fayliga yozish
df.to_excel("test.xlsx", index=False)

In [83]:
# 25. Excel faylini o'qish
df = pd.read_excel("test.xlsx")

In [84]:
# 26. O'qilgan DataFrame'ning oxirgi qatorlari
df.tail()

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [90]:
# 27. CSV faylini o'qish — fayl mavjud bo'lsa
df = pd.read_csv("Titanic-Dataset.csv")

df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [86]:
# 28. JSON faylini o'qish — fayl mavjud bo'lsa
df = pd.read_json("Titanic-Dataset.json")

FileNotFoundError: File Titanic-Dataset.json does not exist

In [ ]:
# 29. Excel faylini saqlash
df.to_excel("test.xlsx", index=False)